language: node_js
node_js:
- '4.2'

env:
  global:
  - secure: HBpd9ktC5DwWASDvSYvm4bbP5Y4jXE39yaCGJWYo3xL/8U+ZRnFmK6Qsf6B9H6YroeNg9fWmLzmaIocjKz++bKdUFc76lswn7Tz66ES5WcpkkHtJPzM1jVCEhEtpMca0hJ1Jq8+d3W+47GOBLOM2xUyuH99nRjMpD9i4fvMOXlM=
  - secure: ZB2eQHZdUqwS4Zq1ujH2teelLqa6Kh2JgDlCbsAMbBgqc6Z0iEcj8r+UvtmxhYNaTGPF1G+XkLpmUsWal3xVk+NRt8bMcGMdSdqqvKtEzyCrqg5AWERlJ8uE6Vz9eC12sEOQbnygtQjJzeE45IK5WHmIo+dv7dP2LhQEPYjk3DU=
  - secure: rs/ZLlofzkhbBtpCkDccyS34Okat1++1yokQWf56OIGaCd9QfMfub6MS0mDpnXaMTJPlqlItJAwkGxtTwCDN2nz6AYZGcfUAnKaJ+cwr8H1BNmSCEXwWBhzgX7jjFhzyP0/Zn/afLAxVjIJIKcYs3lRggz9LpA2rcTZMZaCVbAk=

before_script:
- npm install -g bower
- bower install

script:
- echo 'No test'

before_deploy:
- sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
